// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-company-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var info = {
  name: "Janki Nath & Co. (JCO Fabrics)",
  founded: 1968,
  headOffice: "Mayapuri, New Delhi, India",
  description: "Premium woven fabric manufacturer and exporter since 1968, supplying cotton, linen, jacquard, viscose, twill, yarn-dyed and specialty fabrics to global brands across 20+ countries.",
  monthlyCapacityMeters: 2e6,
  leadTimeDays: "15-30",
  msmeRegistered: true,
  website: "https://jcofabrics.com"
};
var get_company_info_default = defineTool({
  name: "get_company_info",
  title: "Get company info",
  description: "Return high-level information about Janki Nath & Co. (JCO Fabrics) \u2014 founding year, head office, capacity, lead times.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
    structuredContent: info
  })
});

// src/lib/mcp/tools/list-fabrics.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var fabrics = [
  "Cotton",
  "Linen",
  "Jacquard",
  "Viscose",
  "Twill",
  "Yarn-dyed",
  "Specialty fabrics"
];
var list_fabrics_default = defineTool2({
  name: "list_fabrics",
  title: "List fabrics",
  description: "List the fabric categories manufactured and exported by JCO Fabrics.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: fabrics.join(", ") }],
    structuredContent: { fabrics }
  })
});

// src/lib/mcp/tools/list-certifications.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var certifications = [
  { code: "BCI", name: "Better Cotton Initiative" },
  { code: "GOTS", name: "Global Organic Textile Standard" },
  { code: "OCS", name: "Organic Content Standard" },
  { code: "OEKO-TEX", name: "OEKO-TEX Standard 100" }
];
var list_certifications_default = defineTool3({
  name: "list_certifications",
  title: "List certifications",
  description: "List the sustainability and quality certifications held by JCO Fabrics.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      { type: "text", text: certifications.map((c) => `${c.code} \u2014 ${c.name}`).join("\n") }
    ],
    structuredContent: { certifications }
  })
});

// src/lib/mcp/tools/list-weaving-units.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var units = ["Meerut", "Bhiwandi", "Ichalkaranji", "Erode", "Salem", "Surat"];
var headOffice = "Mayapuri, New Delhi";
var list_weaving_units_default = defineTool4({
  name: "list_weaving_units",
  title: "List weaving units",
  description: "List the Indian cities where JCO Fabrics operates weaving units, plus the head office.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: `Weaving units: ${units.join(", ")}. Head Office: ${headOffice}.`
      }
    ],
    structuredContent: { units, headOffice }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
var contact = {
  emails: ["jcofabrics@yahoo.co.in", "manan.jcofabrics@gmail.com"],
  phone: "+91 9891542727",
  website: "https://jcofabrics.com",
  instagram: "https://instagram.com/jankinathandco",
  linkedin: "https://www.linkedin.com/in/manan-bhasin-6a9214417",
  threads: "https://www.threads.com/@jankinathandco"
};
var get_contact_default = defineTool5({
  name: "get_contact",
  title: "Get contact details",
  description: "Return JCO Fabrics contact details \u2014 emails, phone, website, and social profiles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: contact
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "jco-fabrics-mcp",
  title: "JCO Fabrics MCP",
  version: "0.1.0",
  instructions: "Tools for querying public information about Janki Nath & Co. (JCO Fabrics) \u2014 company overview, fabric categories, certifications, weaving unit locations, and contact details.",
  tools: [get_company_info_default, list_fabrics_default, list_certifications_default, list_weaving_units_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
